name = "PairedLinkedLists"
uuid = "7a42b37b-ed3b-477a-9848-3661f53bb718"
authors = ["Tom McGrath <tmcgrath325@gmail.com> and contributors"]
version = "0.2.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
